### ISSUE TITLE
some questions: confused about experiments you did in your paper 

### ISSUE THREAD

**Issue by tiandiao123** [pipiku915/FinMem-LLM-StockTrading#17]
Hi friends:
    I have some questions about how you did your trading experiment in your paper. For example, you just did your trading test or simulate your trading strategy starting in 2022/01, and ending some date in 2024. But I feel since GPT-4 has already seen some critical events when it was training in the past. So, probably, the GPT has already absorbed all of information in the history from 2022 to 2024. So, probably, the entire trading system has already know some info in the future. If so, I don't think it is fair to compare your FINMEM's Tesla cumulative return with other kinds of models' cumulative return over here since other kinds of models such as RL-Agent won't be able to see future data in the future. 

Correct me, if I am wrong ! 
Thank you! 
![image](https://github.com/pipiku915/FinMem-LLM-StockTrading/assets/13476756/246483c5-1d1d-4b70-939f-497818e0c1ea)

**Comment by pipiku915** [comment]
Hi, thanks for your questions.

Regarding your concerns:

Comparison with RL Algorithms: It's important to note that our comparisons are not limited to RL agents alone; we also evaluate against multiple state-of-the-art (SOTA) generative agents as of the publication of our paper. FinMem consistently demonstrated superior performance in all comparisons. Specifically, for the RL algorithms, we extended the training period to approximately 10 years. This extension was to ensure they adequately capture dynamic historical patterns, compensating for their relatively weaker integration of textual features. FinMem's exceptional performance in this comprehensive setup underscores its unique architecture's ability to enhance financial decision-making by effectively capturing market dynamics and aligning the timeliness of multi-source financial data.

Data Leakage Concerns: At the time of our simulation, the cut-off date for GPT-4 (gpt-4-0613) was prior to the commencement of our test simulation, as per the OpenAI official documentation. Thus, concerns regarding potential data leakage are unfounded. Additionally, when comparing various models with the same architectural backbone, FinMem outperformed others, which reinforces that its success is attributed to its framework rather than merely the underlying model training.

Ablation Study Insights: The ablation study reveals that FinMem, using GPT-4 as its backbone, significantly outperformed GPT-4-turbo, which has a later training cutoff date. This indicates that the effectiveness of a language agent system extends beyond merely absorbing extensive available data; it requires an appropriate framework to discern useful insights and provide precise reasoning for specific financial assets and tasks.

Hope that the answer addresses your concern.

**Comment by tiandiao123** [comment]
> Hi, thanks for your questions.
> 
> Regarding your concerns:
> 
> Comparison with RL Algorithms: It's important to note that our comparisons are not limited to RL agents alone; we also evaluate against multiple state-of-the-art (SOTA) generative agents as of the publication of our paper. FinMem consistently demonstrated superior performance in all comparisons. Specifically, for the RL algorithms, we extended the training period to approximately 10 years. This extension was to ensure they adequately capture dynamic historical patterns, compensating for their relatively weaker integration of textual features. FinMem's exceptional performance in this comprehensive setup underscores its unique architecture's ability to enhance financial decision-making by effectively capturing market dynamics and aligning the timeliness of multi-source financial data.
> 
> Data Leakage Concerns: At the time of our simulation, the cut-off date for GPT-4 (gpt-4-0613) was prior to the commencement of our test simulation, as per the OpenAI official documentation. Thus, concerns regarding potential data leakage are unfounded. Additionally, when comparing various models with the same architectural backbone, FinMem outperformed others, which reinforces that its success is attributed to its framework rather than merely the underlying model training.
> 
> Ablation Study Insights: The ablation study reveals that FinMem, using GPT-4 as its backbone, significantly outperformed GPT-4-turbo, which has a later training cutoff date. This indicates that the effectiveness of a language agent system extends beyond merely absorbing extensive available data; it requires an appropriate framework to discern useful insights and provide precise reasoning for specific financial assets and tasks.
> 
> Hope that the answer addresses your concern.

Ok! Thanks for answering!
